version: '3.8'

services:
  react-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args: 
        - --no-cache
    ports:
      - "3000:5173"
    volumes:
      - ./:/app
      - /app/node_modules/
