version: '3.8'

services:
    build:
        container_name: react-dev
        image: react-dev-image
        context: ./frontend
        dockerfile: Dockerfile.dev
        args:
            - --no-cache
    ports:
        - '3000:5173'
    volumes:
        - ./:/app
        - /app/node_modules/

    postgres:
        container_name: our-postgresql
        image: postgres:latest
        ports:
            - '5432:5432'
        volumes:
            - data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - appnet

        backend:
        container_name: node-express
        image: node-express-image
        build:
            context: ./backend/
            dockerfile: Dockerfile.dev
        ports:
            - '8080:3000'
        volumes:
            - ./backend/:/app
        depends_on:
            - postgres
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - PORT=${PORT}
            - FT_UUID=${FT_UUID}
            - FT_SECRET=${FT_SECRET}
            - URL_BACKEND=http://localhost:8080
            - URL_FRONTEND=http://localhost:4040
        networks:
            - appnet

volumes:
    data:
      name: postgres-data