version: '3.8'

services:
  react-dev:
    container_name: react-dev
    build:
      context: ./frontend/
      dockerfile: Dockerfile.dev
      args:
        - --no-cache
    ports:
      - '8000:5173'
    volumes:
      - ./:/app
      - /app/node_modules/

  postgres:
    container_name: postgresql
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    container_name: node-express
    image: node-express-image
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./backend/:/app
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  data:
    name: postgres-data
